name: Test Anomaly
on:
  workflow_dispatch:
jobs:
  run-test:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v4
      - run: python src/detect_cost_anomalies.py --test
